// Generated by tools/build.js. Do not edit this file directly.
var $plugins =
[
{"name":"GachaSystem","status":true,"description":"Gacha / summon system","parameters":{"Currency Type":"variable","Currency ID":"1","Currency Name":"Echo Shards","Single Cost":"100","Multi Cost":"1000","Multi Count":"10","Result Variable":"5","Add To Menu":"true","Menu Command Name":"Summon","Duplicate Refund":"100,300,1000,3000,10000"}},
{"name":"GachaBanners","status":true,"description":"Banner definitions (generated)","parameters":{}},
{"name":"ArchiveData","status":true,"description":"Id tables (generated)","parameters":{}},
{"name":"ArchiveEchoes","status":true,"description":"Limit breaks, level sync, shard drops","parameters":{}},
{"name":"ArchiveHall","status":true,"description":"Archive Hall facilities, bounties and memories","parameters":{}}
];
