// Generates the game-specific plugin files: ArchiveData.js (id tables), GachaBanners.js (banners) and plugins.js.
'use strict';
var ids = require('./ids');
var heroesMod = require('./content_heroes');

function json(o) { return JSON.stringify(o, null, 4); }

function archiveData(ID) {
    var memoryCE = {};
    heroesMod.heroes.forEach(function(h) {
        if (!h.memory) { return; }
        memoryCE[ID.actor[h.key]] = h.memory.map(function(m, i) { return ID.ce['memory_' + h.key + '_' + (i + 1)]; });
    });
    var heroOrder = heroesMod.heroes.map(function(h) { return { key: h.key, id: ID.actor[h.key], name: h.name }; });
    return '// Generated by tools/build.js. Do not edit by hand (edit tools/src and rebuild).\n' +
        '/*:\n * @plugindesc v1.0.0 Id tables for Echoes of the Sundered Archive (generated).\n * @author RPG Maker Gacha\n */\n\n' +
        'var Archive = Archive || {};\n' +
        'Archive.ID = ' + json({ actor: ID.actor, item: ID.item, enemy: ID.enemy, weapon: ID.weapon, armor: ID.armor, skill: ID.skill, ce: ID.ce }) + ';\n' +
        'Archive.memoryCE = ' + json(memoryCE) + ';\n' +
        'Archive.heroOrder = ' + json(heroOrder) + ';\n' +
        'Archive.SWITCH = ' + json(ids.SWITCH) + ';\n' +
        'Archive.VARIABLE = ' + json(ids.VARIABLE) + ';\n';
}

function gachaBanners(ID) {
    function hero(k, w) { return { type: 'actor', id: ID.actor[k], weight: w || 3 }; }
    function item(k, n, w) { return { type: 'item', id: ID.item[k], count: n || 1, weight: w || 2 }; }
    function weapon(k, w) { return { type: 'weapon', id: ID.weapon[k], weight: w || 1 }; }
    function armor(k, w) { return { type: 'armor', id: ID.armor[k], weight: w || 1 }; }
    function gold(n, w) { return { type: 'gold', id: 0, count: n, weight: w || 1 }; }
    function feat(e) { e.featured = true; return e; }

    var banners = [
        {
            id: 'beginner', name: 'Beginner Summon',
            description: 'A gift from the Archive. Ten summons and an SSR or better is guaranteed on the tenth.',
            maxPulls: 10, rates: { R: 50, SR: 36, SSR: 14 },
            pity: { SSR: { soft: 0, hard: 10 }, UR: { soft: 0, hard: 0 } },
            pool: {
                R: [hero('marla'), hero('doran'), hero('fenn')],
                SR: [hero('sera'), hero('tobias'), hero('kael')],
                SSR: [hero('isolde'), hero('brannock')]
            }
        },
        {
            id: 'standard', name: 'Echo Summon',
            description: 'The Archive\'s standing call. All five grades of echo and equipment can answer.\nSSR or better guaranteed by pull 50, UR by pull 90.',
            pool: {
                N: [hero('wick'), hero('pip'), item('inkTonic', 3), item('clarity', 2), item('inkPage', 1, 1), gold(200)],
                R: [hero('marla'), hero('doran'), hero('fenn'), item('fineTonic', 2), item('pressedLeaf', 1), item('inkPage', 2, 1), weapon('blade_R'), weapon('staff_R'), weapon('bow_R')],
                SR: [hero('sera'), hero('tobias'), hero('kael'), weapon('blade_SR'), weapon('tome_SR'), weapon('staff_SR'), armor('robe_SR'), armor('body_SR')],
                SSR: [hero('isolde'), hero('brannock'), weapon('blade_SSR'), weapon('tome_SSR'), armor('shield_SSR')],
                UR: [hero('aurelian', 3), weapon('tome_UR'), armor('charm_UR')]
            }
        },
        {
            id: 'aurelian', name: 'Aurelian\'s Dawn',
            description: 'Rate-up! The First Archivist answers. Aurelian is the featured UR; if you miss him, the next UR is guaranteed to be him.',
            switchId: ids.SWITCH.BANNER_AURELIAN, pityGroup: 'aurelian', rates: { SSR: 7, UR: 1.2 },
            pool: {
                N: [hero('wick'), hero('pip'), item('inkTonic', 3)],
                R: [hero('marla'), hero('doran'), hero('fenn'), item('inkPage', 2, 1)],
                SR: [hero('sera'), hero('tobias'), hero('kael'), weapon('tome_SR')],
                SSR: [feat(hero('isolde', 3)), hero('brannock'), weapon('tome_SSR')],
                UR: [feat(hero('aurelian', 1)), weapon('tome_UR'), armor('charm_UR')]
            }
        },
        {
            id: 'nyx', name: 'Hollow\'s Whisper',
            description: 'Rate-up! A voice from between the lines. Nyx is the featured UR. Losing the 50/50 gives you Aurelian instead.',
            switchId: ids.SWITCH.BANNER_NYX, pityGroup: 'nyx', rates: { SSR: 7, UR: 1.2 },
            pool: {
                N: [hero('wick'), hero('pip'), item('inkTonic', 3)],
                R: [hero('marla'), hero('doran'), hero('fenn'), item('inkPage', 2, 1)],
                SR: [hero('sera'), hero('tobias'), hero('kael'), weapon('blade_SR')],
                SSR: [feat(hero('brannock', 3)), hero('isolde'), weapon('blade_SSR')],
                UR: [feat(hero('nyx', 1)), hero('aurelian', 1)]
            }
        }
    ];
    return '// Generated by tools/build.js. Banner definitions for Echoes of the Sundered Archive.\n' +
        '// Format: see the comment in examples/GachaBanners.sample.js. Edit tools/src/gen_plugins.js and rebuild, or edit this file directly.\n' +
        '/*:\n * @plugindesc v1.0.0 Banner definitions for the Archive (generated).\n * @author RPG Maker Gacha\n */\n\n' +
        'var Gacha = Gacha || {};\nGacha.Banners = Gacha.Banners || [];\nGacha.Banners = Gacha.Banners.concat(' + json(banners) + ');\n';
}

function pluginsJs() {
    function entry(name, desc, params) { return { name: name, status: true, description: desc, parameters: params || {} }; }
    var list = [
        entry('GachaSystem', 'Gacha / summon system', {
            'Currency Type': 'variable', 'Currency ID': String(ids.VARIABLE.SHARDS), 'Currency Name': 'Echo Shards', 'Single Cost': '100',
            'Multi Cost': '1000', 'Multi Count': '10', 'Result Variable': String(ids.VARIABLE.PULL_RESULT), 'Add To Menu': 'true', 'Menu Command Name': 'Summon',
            'Duplicate Refund': '100,300,1000,3000,10000'
        }),
        entry('GachaBanners', 'Banner definitions (generated)'),
        entry('ArchiveData', 'Id tables (generated)'),
        entry('ArchiveEchoes', 'Limit breaks, level sync, shard drops'),
        entry('ArchiveHall', 'Archive Hall facilities, bounties and memories')
    ];
    return '// Generated by tools/build.js. Do not edit this file directly.\nvar $plugins =\n[\n' +
        list.map(function(e) { return JSON.stringify(e); }).join(',\n') + '\n];\n';
}

module.exports = { archiveData: archiveData, gachaBanners: gachaBanners, pluginsJs: pluginsJs };
