// Generated by tools/build.js. Do not edit by hand (edit tools/src and rebuild).
/*:
 * @plugindesc v1.0.0 Id tables for Echoes of the Sundered Archive (generated).
 * @author RPG Maker Gacha
 */

var Archive = Archive || {};
Archive.ID = {
    "actor": {
        "iri": 1,
        "wick": 2,
        "pip": 3,
        "marla": 4,
        "doran": 5,
        "fenn": 6,
        "sera": 7,
        "tobias": 8,
        "kael": 9,
        "isolde": 10,
        "brannock": 11,
        "aurelian": 12,
        "nyx": 13
    },
    "item": {
        "inkTonic": 1,
        "fineTonic": 2,
        "clarity": 3,
        "pressedLeaf": 4,
        "eraser": 5,
        "inkPage": 6,
        "lorePage": 7,
        "indexPage": 8,
        "sigil": 9,
        "echoCache": 10
    },
    "enemy": {
        "fadedWisp": 1,
        "inkWisp": 2,
        "pageMite": 3,
        "huskScribe": 4,
        "tomeMimic": 5,
        "inkSlime": 6,
        "drownedClerk": 7,
        "blotHound": 8,
        "hollowKnight": 9,
        "curatorHusk": 10,
        "unwrittenWarden": 11
    },
    "weapon": {
        "blade_N": 1,
        "spear_N": 2,
        "bow_N": 3,
        "staff_N": 4,
        "tome_N": 5,
        "blade_R": 6,
        "spear_R": 7,
        "bow_R": 8,
        "staff_R": 9,
        "tome_R": 10,
        "blade_SR": 11,
        "spear_SR": 12,
        "bow_SR": 13,
        "staff_SR": 14,
        "tome_SR": 15,
        "blade_SSR": 16,
        "spear_SSR": 17,
        "bow_SSR": 18,
        "staff_SSR": 19,
        "tome_SSR": 20,
        "blade_UR": 21,
        "spear_UR": 22,
        "bow_UR": 23,
        "staff_UR": 24,
        "tome_UR": 25
    },
    "armor": {
        "body_N": 1,
        "robe_N": 2,
        "shield_N": 3,
        "helm_N": 4,
        "charm_N": 5,
        "body_R": 6,
        "robe_R": 7,
        "shield_R": 8,
        "helm_R": 9,
        "charm_R": 10,
        "body_SR": 11,
        "robe_SR": 12,
        "shield_SR": 13,
        "helm_SR": 14,
        "charm_SR": 15,
        "body_SSR": 16,
        "robe_SSR": 17,
        "shield_SSR": 18,
        "helm_SSR": 19,
        "charm_SSR": 20,
        "body_UR": 21,
        "robe_UR": 22,
        "shield_UR": 23,
        "helm_UR": 24,
        "charm_UR": 25
    },
    "skill": {
        "attack": 1,
        "guard": 2,
        "annotate": 3,
        "index": 4,
        "revise": 5,
        "crossReference": 6,
        "lanternSwing": 7,
        "holdTheLight": 8,
        "lastLamp": 9,
        "pageDash": 10,
        "paperCut": 11,
        "specialDelivery": 12,
        "mendScript": 13,
        "blessedMargin": 14,
        "fairCopy": 15,
        "shieldAudit": 16,
        "ledgerSlam": 17,
        "balancedBooks": 18,
        "quickQuill": 19,
        "pinningShot": 20,
        "volleyOfFootnotes": 21,
        "inkBolt": 22,
        "blotStorm": 23,
        "inkfall": 24,
        "tollOfCourage": 25,
        "silencingChime": 26,
        "grandPeal": 27,
        "marginalia": 28,
        "flurryOfNotes": 29,
        "redline": 30,
        "chartedGale": 31,
        "markTheRoute": 32,
        "cartographersFolio": 33,
        "chapterWall": 34,
        "dogEar": 35,
        "finalChapter": 36,
        "firstLight": 37,
        "indexOfAges": 38,
        "illuminatedEdition": 39,
        "unwritePage": 40,
        "erasure": 41,
        "blankVerse": 42,
        "inkSpit": 43,
        "enemyPaperCut": 44,
        "quillStab": 45,
        "scribbleOver": 46,
        "chomp": 47,
        "pageGust": 48,
        "engulf": 49,
        "overdue": 50,
        "coldStamp": 51,
        "lunge": 52,
        "voidSlash": 53,
        "hollowGuard": 54,
        "bookBarrage": 55,
        "summonWisps": 56,
        "erasePage": 57,
        "blankOut": 58,
        "chainSwing": 59,
        "summonHounds": 60
    },
    "ce": {
        "memory_wick_1": 1,
        "memory_wick_2": 2,
        "memory_pip_1": 3,
        "memory_pip_2": 4,
        "memory_marla_1": 5,
        "memory_marla_2": 6,
        "memory_doran_1": 7,
        "memory_doran_2": 8,
        "memory_fenn_1": 9,
        "memory_fenn_2": 10,
        "memory_sera_1": 11,
        "memory_sera_2": 12,
        "memory_tobias_1": 13,
        "memory_tobias_2": 14,
        "memory_kael_1": 15,
        "memory_kael_2": 16,
        "memory_isolde_1": 17,
        "memory_isolde_2": 18,
        "memory_brannock_1": 19,
        "memory_brannock_2": 20,
        "memory_aurelian_1": 21,
        "memory_aurelian_2": 22,
        "memory_nyx_1": 23,
        "memory_nyx_2": 24,
        "summonWisps": 25,
        "summonHounds": 26,
        "useCache": 27,
        "quillTalk": 28,
        "expeditionGate": 29,
        "altar": 30,
        "firstSummon": 31,
        "restWing": 32,
        "saveCrystal": 33,
        "healCandles": 34,
        "retreat": 35,
        "deskMenu": 36,
        "bounty": 37,
        "upgradeMenu": 38,
        "upgradeFacility": 39,
        "forgeShop": 40,
        "memoryStand": 41
    }
};
Archive.memoryCE = {
    "2": [
        1,
        2
    ],
    "3": [
        3,
        4
    ],
    "4": [
        5,
        6
    ],
    "5": [
        7,
        8
    ],
    "6": [
        9,
        10
    ],
    "7": [
        11,
        12
    ],
    "8": [
        13,
        14
    ],
    "9": [
        15,
        16
    ],
    "10": [
        17,
        18
    ],
    "11": [
        19,
        20
    ],
    "12": [
        21,
        22
    ],
    "13": [
        23,
        24
    ]
};
Archive.heroOrder = [
    {
        "key": "iri",
        "id": 1,
        "name": "Iri"
    },
    {
        "key": "wick",
        "id": 2,
        "name": "Wick"
    },
    {
        "key": "pip",
        "id": 3,
        "name": "Pip"
    },
    {
        "key": "marla",
        "id": 4,
        "name": "Marla"
    },
    {
        "key": "doran",
        "id": 5,
        "name": "Doran"
    },
    {
        "key": "fenn",
        "id": 6,
        "name": "Fenn"
    },
    {
        "key": "sera",
        "id": 7,
        "name": "Sera"
    },
    {
        "key": "tobias",
        "id": 8,
        "name": "Tobias"
    },
    {
        "key": "kael",
        "id": 9,
        "name": "Kael"
    },
    {
        "key": "isolde",
        "id": 10,
        "name": "Isolde"
    },
    {
        "key": "brannock",
        "id": 11,
        "name": "Brannock"
    },
    {
        "key": "aurelian",
        "id": 12,
        "name": "Aurelian"
    },
    {
        "key": "nyx",
        "id": 13,
        "name": "Nyx"
    }
];
Archive.SWITCH = {
    "PROLOGUE_DONE": 1,
    "FIRST_SUMMON_DONE": 2,
    "STACKS_OPEN": 3,
    "STACKS_BOSS_DONE": 4,
    "INK_OPEN": 5,
    "INK_BOSS_DONE": 6,
    "SLICE_COMPLETE": 7,
    "QUILL_INTRO": 8,
    "BANNER_AURELIAN": 10,
    "BANNER_NYX": 11,
    "FORGE_UNLOCKED": 12,
    "DESK_UNLOCKED": 13,
    "SHRINE_UNLOCKED": 14,
    "LEVER_STACKS": 20,
    "LEVER_INK": 21
};
Archive.VARIABLE = {
    "SHARDS": 1,
    "CHAPTER": 2,
    "TEMP": 3,
    "TEMP2": 4,
    "PULL_RESULT": 5,
    "SHOW_A": 11,
    "SHOW_B": 12,
    "SHOW_C": 13,
    "SHOW_D": 14,
    "SHOW_E": 15
};
