// Generated by tools/build.js. Banner definitions for Echoes of the Sundered Archive.
// Format: see the comment in examples/GachaBanners.sample.js. Edit tools/src/gen_plugins.js and rebuild, or edit this file directly.
/*:
 * @plugindesc v1.0.0 Banner definitions for the Archive (generated).
 * @author RPG Maker Gacha
 */

var Gacha = Gacha || {};
Gacha.Banners = Gacha.Banners || [];
Gacha.Banners = Gacha.Banners.concat([
    {
        "id": "beginner",
        "name": "Beginner Summon",
        "description": "A gift from the Archive. Ten summons and an SSR or better is guaranteed on the tenth.",
        "maxPulls": 10,
        "rates": {
            "R": 50,
            "SR": 36,
            "SSR": 14
        },
        "pity": {
            "SSR": {
                "soft": 0,
                "hard": 10
            },
            "UR": {
                "soft": 0,
                "hard": 0
            }
        },
        "pool": {
            "R": [
                {
                    "type": "actor",
                    "id": 4,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 5,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 6,
                    "weight": 3
                }
            ],
            "SR": [
                {
                    "type": "actor",
                    "id": 7,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 8,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 9,
                    "weight": 3
                }
            ],
            "SSR": [
                {
                    "type": "actor",
                    "id": 10,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 11,
                    "weight": 3
                }
            ]
        }
    },
    {
        "id": "standard",
        "name": "Echo Summon",
        "description": "The Archive's standing call. All five grades of echo and equipment can answer.\nSSR or better guaranteed by pull 50, UR by pull 90.",
        "pool": {
            "N": [
                {
                    "type": "actor",
                    "id": 2,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 3,
                    "weight": 3
                },
                {
                    "type": "item",
                    "id": 1,
                    "count": 3,
                    "weight": 2
                },
                {
                    "type": "item",
                    "id": 3,
                    "count": 2,
                    "weight": 2
                },
                {
                    "type": "item",
                    "id": 6,
                    "count": 1,
                    "weight": 1
                },
                {
                    "type": "gold",
                    "id": 0,
                    "count": 200,
                    "weight": 1
                }
            ],
            "R": [
                {
                    "type": "actor",
                    "id": 4,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 5,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 6,
                    "weight": 3
                },
                {
                    "type": "item",
                    "id": 2,
                    "count": 2,
                    "weight": 2
                },
                {
                    "type": "item",
                    "id": 4,
                    "count": 1,
                    "weight": 2
                },
                {
                    "type": "item",
                    "id": 6,
                    "count": 2,
                    "weight": 1
                },
                {
                    "type": "weapon",
                    "id": 6,
                    "weight": 1
                },
                {
                    "type": "weapon",
                    "id": 9,
                    "weight": 1
                },
                {
                    "type": "weapon",
                    "id": 8,
                    "weight": 1
                }
            ],
            "SR": [
                {
                    "type": "actor",
                    "id": 7,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 8,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 9,
                    "weight": 3
                },
                {
                    "type": "weapon",
                    "id": 11,
                    "weight": 1
                },
                {
                    "type": "weapon",
                    "id": 15,
                    "weight": 1
                },
                {
                    "type": "weapon",
                    "id": 14,
                    "weight": 1
                },
                {
                    "type": "armor",
                    "id": 12,
                    "weight": 1
                },
                {
                    "type": "armor",
                    "id": 11,
                    "weight": 1
                }
            ],
            "SSR": [
                {
                    "type": "actor",
                    "id": 10,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 11,
                    "weight": 3
                },
                {
                    "type": "weapon",
                    "id": 16,
                    "weight": 1
                },
                {
                    "type": "weapon",
                    "id": 20,
                    "weight": 1
                },
                {
                    "type": "armor",
                    "id": 18,
                    "weight": 1
                }
            ],
            "UR": [
                {
                    "type": "actor",
                    "id": 12,
                    "weight": 3
                },
                {
                    "type": "weapon",
                    "id": 25,
                    "weight": 1
                },
                {
                    "type": "armor",
                    "id": 25,
                    "weight": 1
                }
            ]
        }
    },
    {
        "id": "aurelian",
        "name": "Aurelian's Dawn",
        "description": "Rate-up! The First Archivist answers. Aurelian is the featured UR; if you miss him, the next UR is guaranteed to be him.",
        "switchId": 10,
        "pityGroup": "aurelian",
        "rates": {
            "SSR": 7,
            "UR": 1.2
        },
        "pool": {
            "N": [
                {
                    "type": "actor",
                    "id": 2,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 3,
                    "weight": 3
                },
                {
                    "type": "item",
                    "id": 1,
                    "count": 3,
                    "weight": 2
                }
            ],
            "R": [
                {
                    "type": "actor",
                    "id": 4,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 5,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 6,
                    "weight": 3
                },
                {
                    "type": "item",
                    "id": 6,
                    "count": 2,
                    "weight": 1
                }
            ],
            "SR": [
                {
                    "type": "actor",
                    "id": 7,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 8,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 9,
                    "weight": 3
                },
                {
                    "type": "weapon",
                    "id": 15,
                    "weight": 1
                }
            ],
            "SSR": [
                {
                    "type": "actor",
                    "id": 10,
                    "weight": 3,
                    "featured": true
                },
                {
                    "type": "actor",
                    "id": 11,
                    "weight": 3
                },
                {
                    "type": "weapon",
                    "id": 20,
                    "weight": 1
                }
            ],
            "UR": [
                {
                    "type": "actor",
                    "id": 12,
                    "weight": 1,
                    "featured": true
                },
                {
                    "type": "weapon",
                    "id": 25,
                    "weight": 1
                },
                {
                    "type": "armor",
                    "id": 25,
                    "weight": 1
                }
            ]
        }
    },
    {
        "id": "nyx",
        "name": "Hollow's Whisper",
        "description": "Rate-up! A voice from between the lines. Nyx is the featured UR. Losing the 50/50 gives you Aurelian instead.",
        "switchId": 11,
        "pityGroup": "nyx",
        "rates": {
            "SSR": 7,
            "UR": 1.2
        },
        "pool": {
            "N": [
                {
                    "type": "actor",
                    "id": 2,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 3,
                    "weight": 3
                },
                {
                    "type": "item",
                    "id": 1,
                    "count": 3,
                    "weight": 2
                }
            ],
            "R": [
                {
                    "type": "actor",
                    "id": 4,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 5,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 6,
                    "weight": 3
                },
                {
                    "type": "item",
                    "id": 6,
                    "count": 2,
                    "weight": 1
                }
            ],
            "SR": [
                {
                    "type": "actor",
                    "id": 7,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 8,
                    "weight": 3
                },
                {
                    "type": "actor",
                    "id": 9,
                    "weight": 3
                },
                {
                    "type": "weapon",
                    "id": 11,
                    "weight": 1
                }
            ],
            "SSR": [
                {
                    "type": "actor",
                    "id": 11,
                    "weight": 3,
                    "featured": true
                },
                {
                    "type": "actor",
                    "id": 10,
                    "weight": 3
                },
                {
                    "type": "weapon",
                    "id": 16,
                    "weight": 1
                }
            ],
            "UR": [
                {
                    "type": "actor",
                    "id": 13,
                    "weight": 1,
                    "featured": true
                },
                {
                    "type": "actor",
                    "id": 12,
                    "weight": 1
                }
            ]
        }
    }
]);
