// Generates docs/roster.md (heroes, skills, enemies, flags) straight from the game data so it can't drift.
// Usage: node tools/gen_docs.js
'use strict';
var fs = require('fs');
var path = require('path');
var db = require('./src/db');
var common = require('./src/story_common');
var heroesMod = require('./src/content_heroes');
var world = require('./src/content_world');
var ids = require('./src/ids');

var d = db.build({ commonEvents: common.specs() });
var skillById = {};
d.Skills.forEach(function(s) { if (s) { skillById[s.id] = s; } });
var EL = ids.ELEMENT_NAMES;
var lines = [];
function out(s) { lines.push(s === undefined ? '' : s); }

out('# Roster and data reference');
out('');
out('Generated by `node tools/gen_docs.js` from the game data. Do not edit by hand.');
out('');
out('## Echoes (heroes)');
out('');
out('Rarity multiplies every stat: N x0.85, R x1.00, SR x1.12, SSR x1.25, UR x1.40. Each limit break adds +6% more (max 5). The Burst skill is learned at limit break 3.');
out('');
out('| # | Name | Rarity | Class | Weapon | Arts | Burst (TP) | Starts at |');
out('|---|------|--------|-------|--------|------|------------|-----------|');
heroesMod.heroes.forEach(function(h) {
    var a = d.Actors[d.ID.actor[h.key]], cls = d.Classes[a.classId];
    var arts = cls.learnings.filter(function(l) { return skillById[l.skillId].stypeId !== 2; }).map(function(l) { return skillById[l.skillId].name + ' (Lv' + l.level + ')'; });
    var burstL = cls.learnings.filter(function(l) { return skillById[l.skillId].stypeId === 2; })[0];
    var burstM = /<Burst: (\d+)>/.exec(a.note), burst = burstL ? skillById[burstL.skillId] : (burstM ? skillById[Number(burstM[1])] : null);
    var wt = ['', 'Blade', 'Spear', 'Bow', 'Staff', 'Tome'][d.Weapons[a.equips[0]].wtypeId];
    out('| ' + a.id + ' | **' + h.name + '** (' + h.title + ') | ' + (h.rarity || 'Story') + ' | ' + cls.name + ' | ' + wt + ' | ' +
        arts.join(', ') + ' | ' + (burst ? burst.name + ' (' + burst.tpCost + ')' + (burstL ? ' at Lv' + burstL.level : '') : '-') + ' | Lv ' + a.initialLevel + ' |');
});
out('');
out('### Skill details');
out('');
out('| Skill | Type | Cost | Scope | Effect |');
out('|-------|------|------|-------|--------|');
var SCOPE = ['none', '1 enemy', 'all enemies', '1 random enemy', '2 random enemies', '3 random enemies', '4 random enemies', '1 ally', 'all allies', '1 fallen ally', 'all fallen allies', 'self'];
d.Skills.forEach(function(s) {
    if (!s || s.id <= 2 || s.stypeId === 0) { return; }
    var cost = s.stypeId === 2 ? s.tpCost + ' TP' : s.mpCost + ' MP';
    out('| ' + s.name + ' | ' + (s.stypeId === 2 ? 'Burst' : 'Art') + ' | ' + cost + ' | ' + SCOPE[s.scope] + ' | ' + s.description + ' |');
});
out('');
out('## Enemies');
out('');
out('Shards are Echo Shards (the summon currency). 100 shards = 1 pull.');
out('');
out('| Enemy | HP | ATK | DEF | MAT | MDF | AGI | EXP | Gold | Shards | Weak to | Resists |');
out('|-------|----|-----|-----|-----|-----|-----|-----|------|--------|---------|---------|');
d.Enemies.forEach(function(e) {
    if (!e) { return; }
    var weak = [], res = [];
    e.traits.forEach(function(t) { if (t.code === 11) { (t.value > 1 ? weak : res).push(EL[t.dataId] + ' x' + t.value); } });
    out('| ' + e.name + ' | ' + e.params[0] + ' | ' + e.params[2] + ' | ' + e.params[3] + ' | ' + e.params[4] + ' | ' + e.params[5] + ' | ' + e.params[6] + ' | ' +
        e.exp + ' | ' + e.gold + ' | ' + /<Shards: (\d+)>/.exec(e.note)[1] + ' | ' + weak.join(', ') + ' | ' + res.join(', ') + ' |');
});
out('');
out('## Game switches and variables');
out('');
out('| Switch | Meaning |');
out('|--------|---------|');
Object.keys(ids.SWITCH).forEach(function(k) { out('| ' + ids.SWITCH[k] + ' | ' + k + ' |'); });
out('');
out('| Variable | Meaning |');
out('|----------|---------|');
Object.keys(ids.VARIABLE).forEach(function(k) { out('| ' + ids.VARIABLE[k] + ' | ' + k + ' |'); });
out('');
fs.writeFileSync(path.join(__dirname, '..', 'docs', 'roster.md'), lines.join('\n'));
console.log('wrote docs/roster.md');
