// Installs the game into an RPG Maker MV project.
//   1. In RPG Maker MV create a new, blank project (File > New Project).
//   2. node tools/install.js "<path to that project folder>"
// Copies data/, img/ (tilesets, enemies, battlebacks, title) and js/plugins into the project and MERGES the
// game's settings into the project's own System.json, so its terms, sounds and engine settings are kept.
'use strict';
var fs = require('fs');
var path = require('path');
var system = require('./src/system');

var root = path.join(__dirname, '..');
var target = process.argv[2];
var dry = process.argv.indexOf('--dry-run') >= 0;
if (!target) { console.log('Usage: node tools/install.js <MV project folder> [--dry-run]'); process.exit(1); }
target = path.resolve(target);

if (!fs.existsSync(path.join(target, 'js', 'rpg_core.js')) && !fs.existsSync(path.join(target, 'Game.rpgproject'))) {
    console.log('Warning: ' + target + ' does not look like an RPG Maker MV project (no js/rpg_core.js or Game.rpgproject).');
    console.log('Create a blank project in the MV editor first, then point this script at it.');
    if (!dry) { process.exit(1); }
}

function copy(rel, skip) {
    var from = path.join(root, rel), to = path.join(target, rel);
    if (!fs.existsSync(from)) { return 0; }
    var n = 0;
    (function walk(src, dst) {
        var st = fs.statSync(src);
        if (st.isDirectory()) {
            if (!dry) { fs.mkdirSync(dst, { recursive: true }); }
            fs.readdirSync(src).forEach(function(f) { walk(path.join(src, f), path.join(dst, f)); });
        } else if (!(skip && skip(src))) {
            if (!dry) { fs.copyFileSync(src, dst); }
            n++;
        }
    })(from, to);
    return n;
}

var counts = {};
counts.data = copy('data', function(f) { return path.basename(f) === 'System.json'; });
['tilesets', 'enemies', 'battlebacks1', 'battlebacks2', 'titles1'].forEach(function(d) { counts['img/' + d] = copy(path.join('img', d)); });
counts.plugins = copy(path.join('js', 'plugins'));

// merge System.json
var ours = JSON.parse(fs.readFileSync(path.join(root, 'data', 'System.json'), 'utf8'));
var sysPath = path.join(target, 'data', 'System.json'), merged;
if (fs.existsSync(sysPath)) {
    var theirs = JSON.parse(fs.readFileSync(sysPath, 'utf8'));
    system.PATCH_KEYS.forEach(function(k) { theirs[k] = ours[k]; });
    merged = theirs;
} else { merged = ours; }
if (!dry) { fs.mkdirSync(path.dirname(sysPath), { recursive: true }); fs.writeFileSync(sysPath, JSON.stringify(merged)); }

// merge js/plugins.js (keep any other plugins the project already uses)
var pjPath = path.join(target, 'js', 'plugins.js'), mine = new Function(fs.readFileSync(path.join(root, 'js', 'plugins.js'), 'utf8') + '; return $plugins;')();
var others = [];
if (fs.existsSync(pjPath)) {
    try {
        others = new Function(fs.readFileSync(pjPath, 'utf8') + '; return $plugins;')().filter(function(p) { return !mine.some(function(m) { return m.name === p.name; }); });
    } catch (e) { console.log('Could not read the existing plugins.js, replacing it.'); }
}
var all = mine.concat(others);
if (!dry) {
    fs.mkdirSync(path.dirname(pjPath), { recursive: true });
    fs.writeFileSync(pjPath, '// Generated by RPG Maker MV Gacha install script.\nvar $plugins =\n[\n' + all.map(function(e) { return JSON.stringify(e); }).join(',\n') + '\n];\n');
}

console.log((dry ? '[dry run] would install' : 'Installed') + ' into ' + target);
Object.keys(counts).forEach(function(k) { console.log('  ' + k + ': ' + counts[k] + ' file(s)'); });
console.log('  System.json merged (' + system.PATCH_KEYS.length + ' settings), plugins.js: ' + all.length + ' plugin(s)');
console.log('\nOpen the project in RPG Maker MV and press Test Play (Ctrl+R). The game begins in The Waking Room.');
